### ISSUE TITLE
Can't get KiTTY working with local files

### ISSUE THREAD

**Issue by deanhouseholder** [psistorm/keypirinha-kitty#1]
I'm not sure if I'm doing something wrong, but I want to use Keypirana with KiTTY in a portable mode.  I have edited the KiTTY Configuration file and added the following:

[KiTTY]
label = KiTTY
file_based = yes
path = C:\Utils\SSH\kitty.exe

Can you help me understand how to configure it?

**Comment by psistorm** [comment]
My config looks like:

```
[dist/official]
enable = yes
label = ssh
file_based = yes
path = "C:\Tools\kitty\"
```

So first of all, I guess the config will not be found because your ini category is not prefixed with `[dist/...]`. 

The next thing is you're providing the complete exe path, but the script expects only the path in which the exe file is located, whereas the exe should be named `kitty.exe` (this is hardcoded)

**Comment by deanhouseholder** [comment]
I changed mine to:

```
[dist/official]
enable = yes
label = ssh
file_based = yes
path = "C:\Utils\SSH\"
```

And it still does not work.  I type "ssh" in Keypirinha and I can't figure out how to get it to pull up my sessions.  I'm using the kitty portable version with a "Sessions" folder in the same directory as kitty.exe.  Is that how you have configured yours?

**Comment by psistorm** [comment]
Yes that's the same configuration as I'm using it. You don't hit enter on the item, but rather `<Tab>` which should show up the sessions then. If you hit enter on the item it just launches Kitty.

**Comment by deanhouseholder** [comment]
Thanks for the help.  I got it working now!

But could I make a feature request?  It doesn't currently recognize folders.  I've got over 400 servers organized into folders, so without the ability to navigate folders, this plugin isn't useful.

**Comment by psistorm** [comment]
You're welcome. Sure, I added a new issue for your request and will close this one. The new issue is #2

**Comment by psistorm** [comment]
Check out v1.0.3 in release section. I added the capability to search also files in subfolders.
