### ISSUE TITLE
Support folders for KiTTY Sessions

### ISSUE THREAD

**Issue by psistorm** [psistorm/keypirinha-kitty#2]
KiTTY currently does not recognize folders. With a lot of servers and folders the plugin is not useful.

**Comment by psistorm** [comment]
Added capability to search through folders recursively

**Comment by deanhouseholder** [comment]
Thank you for working on this!  Unfortunately, I can't get it to work.
I've installed the updated v1.0.3 plugin and restarted keypirinha and now when I type "ssh" and press tab, I see a list of the all options nested in folders!  But when I select one and press enter, it simply opens up kitty.exe's main window without opening to the session.  Maybe there's some configuration that I simply need to do to make this work?
